### ISSUE TITLE
Properties and Tulpe not found

### ISSUE THREAD

**Issue by duchonic** [viam-labs/generator-viam-module#2]
I created a simple custom motor module. If i run.sh both return values from is_powered() and get_properties() are unknown. I replaced them with both bool values and then the code runs.

`2023-07-16 09:46:14,794         ERROR   viam (__init__.py:34)   [ERROR] Uncaught exception
Traceback (most recent call last):
  File "/Users/nicolasduchoud/.platformio/python3/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/nicolasduchoud/.platformio/python3/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/nicolasduchoud/Documents/20-29_work/25_viam/test/src/__init__.py", line 8, in <module>
    from .test import test
  File "/Users/nicolasduchoud/Documents/20-29_work/25_viam/test/src/test.py", line 18, in <module>
    class test(Motor, Reconfigurable):
  File "/Users/nicolasduchoud/Documents/20-29_work/25_viam/test/src/test.py", line 154, in test
    ) -> Properties:
NameError: name 'Properties' is not defined`

**Comment by duchonic** [comment]
Maye Tuple can be solved by 
`from typing import Tuple`

Are the Properties already known and defined or do i have to implement them?

**Comment by duchonic** [comment]
And for the Properties its `Motor.Properties` as return value

**Comment by mcvella** [comment]
Great catch, I will look to figure out how to add logic to pull these into the generated code

**Comment by mcvella** [comment]
@duchonic - PR here if you want to take a look/review: https://github.com/viam-labs/generator-viam-module/pull/3

**Comment by mcvella** [comment]
work complete here: https://github.com/viam-labs/generator-viam-module/pull/3
